# fly.toml app configuration file generated for expense-bot-il4p2g on 2026-05-09T11:11:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'expense-bot-il4p2g'
primary_region = 'ams'

[build]

[machines]
  min_machines_running = 1
  max_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
